name: amplify_codegen
description: A code generator for Amplify models.
version: 0.1.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.1.2
  code_builder: ^4.1.0
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.1
  dart_style: ^2.2.0
  gql: ^0.13.1-0
  uuid: ^3.0.5

dev_dependencies:
  amplify_lints: ^1.0.0
  build_runner: ^2.0.0
  built_value_generator: ^8.1.2
  path: ^1.8.0
  test: ^1.19.5

executables:
  amplify-codegen: amplify_codegen